#!/bin/bash
#----------AUTHOR------------
	# Jacob Salmela	
	# 18 July 2013
	# https://github.com/jakesalmela/

#---------DESCRIPTION--------
	# Pauses Spotify and plays a Star Trek klaxon sound when a certain IP address is detected

#-----------USAGE------------
	# Save as a geeklet with a refresh of every 2-10 seconds
	
#----------RESOURCES---------
	# https://github.com/dronir/SpotifyControl
	# http://www.trekcore.com/audio/

#----------------------------
#-----------SCRIPT-----------
#----------------------------
# Ping once, sending output into the Sarlaac Pit
ping -c 1 10.x.x.x &> /dev/null

# If the last command executed without error (meaning the IP address was detected) then 
if [ $? = 0 ];then

	# Send a ssh command to pause the music on the computer
	ssh <user>@<ip_addres> "osascript /Users/Shared/SpotifyControl.scpt pause" &> /dev/null
	
	# Play the alert sound effect,
	ssh <user>@<ip_address> "afplay /Users/Shared/alert09.mp3"
	
	# And display that there is an intruder on the screen
	echo "Intruder alert! Single-user mode detected!"
fi
